// merchant_id - PayHere Merchant ID
// return_url - URL to redirect users when success
// cancel_url - URL to redirect users when cancelled
// notify_url - URL to callback the status of the payment
// first_name - Customer’s First Name
// last_name - Customer’s Last Name
// email - Customer’s Email
// phone - Customer’s Phone No
// address - Customer’s Address Line1 + Line2
// city - Customer’s City
// country - Customer’s Country
// order_id - Order ID generated by the merchant
// items - Item title or Order/Invoice number
// currency - Currency Code (LKR/USD)
// recurrence - Recurring Period (A number & a word separated by a space such as 2 Week, 1 Month, 6 Month, 1 Year, etc. Word can be ‘Week’, ‘Month’ or ‘Year’ in singular. Number can be any to define recurrent period with word.)
// duration - Duration to charge ('Forever' if there's no time limitation. Otherwise a Number & a word separated by a space as 1 Month, 1 Year, 3 Year, ect. Word can be ‘Week’, ‘Month’, ‘Year’. Number should be compatible with the word in recurrence.)
// amount - Total Payment Amount (eg. 1000.00)
// hash - Generated hash value as mentioned below (*Required from 2023-01-16)


// Optional POST Parameters

// delivery_address - Delivery Address Line1 + Line2
// delivery_city - Delivery City
// delivery_country - Delivery Country
// item_name_1 - Name of Item 1
// item_number_1 - Model number of Item 1
// amount_1 - Unit amount of Item 1
// quantity_1 - Quantity of Item 1
// item_name_2 - Name of Item 2
// item_number_2 - Model number of Item 2
// amount_2 - Unit amount of Item 2
// quantity_2 - Quantity of Item 2
// (You can list rest of the items also like this)
// platform - Referring Platform
// custom_1 - Custom param 1 set by merchant
// custom_2 - Custom param 2 set by merchant
// startup_fee - Additional fee or discount in 1st payment occurance

export interface PaymentRequest {
    merchent_id: string;
    return_url: string;
    cancel_url: string;
    notify_url: string;
    first_name: string;
    last_name: string;
    email: string;
    phone: string;
    address: string;
    city: string;
    country: string;
    order_id: string;
    items: string;
    currency: string;
    recurrence: string;
    duration: string;
    amount: number;
    hash: string;
    delivery_address?: string;
    delivery_city?: string;
    delivery_country?: string;
    item_name_1?: string;
    item_number_1?: string;
    amount_1?: number;
    quantity_1?: number;
    item_name_2?: string;
    item_number_2?: string;
    amount_2?: number;
    quantity_2?: number;
    platform?: string;
    custom_1?: string;
    custom_2?: string;
    startup_fee?: number;

}

// merchant_id - PayHere Merchant ID of the merchant
// order_id - Order ID sent by Merchant to Checkout page
// payment_id - Unique Payment ID generated by PayHere for the processed payment
// subscription_id - Unique Subscription ID generated by PayHere for the authorized subscription
// payhere_amount - Total Amount of the payment
// payhere_currency - Currency code of the payment (LKR/USD)
// status_code - Payment status code (2, 0, -1, -2, -3)
// md5sig - Encrypted signature to verify the payment
// custom_1 - Custom param 1 sent by merchant to Checkout page
// custom_2 - Custom param 2 sent by merchant to Checkout page
// method - Payment method selected by the customer. (VISA, MASTER)
// status_message - Message received from payment gateway which the customer tried to pay
// recurring - Whether payment is a recurring payment (1:recurring, 0: not-recurring)
// message_type - Status message (AUTHORIZATION_SUCCESS, AUTHORIZATION_FAILED, RECURRING_INSTALLMENT_SUCCESS, RECURRING_INSTALLMENT_FAILED, RECURRING_COMPLETE, RECURRING_STOPPED)
// item_recurrence - How often it charges. eg. 1 Month
// item_duration - How long it charges. eg. 1 Year
// item_rec_status - Status of recurring subscription. (0: active, -1: cancelled, 1: completed)
// item_rec_date_next - Date of next recurring installment (YYYY-MM-DD)
// item_rec_install_paid - Number of successful recurring installments charged

// If the customer made the payment by VISA or MASTER credit/debit card, following parameters will also be available.
// card_holder_name - Card Holder Name
// card_no - Masked card number (Ex: ************4564)
// card_expiry - Card expiry in format MMYY (Ex: 0122)


export interface PayementReponse{
    merchant_id: string;
    order_id: string;
    payment_id: string;
    subscription_id: string;
    payhere_amount: number;
    payhere_currency: string;
    status_code: number;
    md5sig: string;
    custom_1: string;
    custom_2: string;
    method: string;
    status_message: string;
    recurring: number;
    message_type: string;
    item_recurrence: string;
    item_duration: string;
    item_rec_status: number;
    item_rec_date_next: string;
    item_rec_install_paid: number;
    card_holder_name: string;
    card_no: string;
    card_expiry: string;

}